version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "TaskDef"
        LoadBalancerInfo:
          ContainerName: "nodejs"
          ContainerPort: 3000
