version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: latest
        commands:
            - echo "installing something"
    pre_build:
        commands: 
            - echo "we are in the pre build phase"
            # Login to Docker Hub (replace with your Docker Hub username and password or use secrets)
            - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            # Login to ECR
            - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
    build:
        commands:
            - echo "we are in the build blocks"
            - docker build -t nodejs-v2:latest .
            - docker tag nodejs-v2:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/nodejs-v2:latest
    post_build:
        commands:
                - echo "we are in the post build phase"
                - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/nodejs-v2:latest

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - Dockerfile
    - build/**/*

